; ==============================================================================
; HALO Clock Firmware
; PlatformIO Configuration
; ==============================================================================

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_src_filter =
    +<*>
    -<Button.cpp>
    -<Notifications.cpp>
    -<Settings.cpp>
    -<Themes.cpp>
    -<Weather.cpp>
    -<WebPortal.cpp>

build_unflags =
    -std=gnu++11

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DHALO_VERSION=\"0.1.0-alpha\"
    -std=gnu++17
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.1
    olikraus/U8g2 @ ^2.36.5
    tzapu/WiFiManager @ ^2.0.17

monitor_filters =
    colorize
    esp32_exception_decoder

upload_protocol = esptool
