name: Firmware build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build HALO CST firmware
        run: platformio run --project-conf platformIO.ini
